name: Android Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      # ← Add this step right after the build
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: bluetooth-jammer-apk
          path: app/build/outputs/apk/debug/app-debug.apk
